### ISSUE TITLE
Functionality of argument "rmZeroCov" in `read.bismark`

### ISSUE THREAD

**Issue by nhejazi** [kasperdanielhansen/bsseq#38]
Perhaps I'm using a version of the R/bsseq package that's too old (v1.6.0, installed via Bioconductor's `biocLite`), but it appears that the argument rmZeroCov is not actually doing anything. I have just run the `read.bismark` function twice on my local machine (using `rmZeroCov = TRUE` and `rmZeroCov = FALSE`), with both returning objects of the same size. What's more the matrices returned by `getCoverage(... , type = "Cov")` on both of these BSseq objects include many CpG loci with values of 0. Though these are easily removed with a line or two of extra code, the function does not return any warning that loci of coverage zero are present in the matrix -- and, use of `getMeth()` returns NaN for all such loci. Looking at the code under branch master for `read.bismark`, I cannot actually find a place where the rmZeroCov argument gets used (it seems to get passed along through various functions with no actual purpose). I'd be glad to help fix this if it is actually a problem -- any clarification would be appreciated @PeteHaitch

**Comment by PeteHaitch** [comment]
Yes, this was a bug in older versions of bsseq, fixed in `v1.7.10`(https://github.com/kasperdanielhansen/bsseq/pull/29) and available as of `v1.8.0` in the Bioconductor release branch through `biocLite()`. If you update to the latest version of Bioconductor (recommended in any case) this should be fixed

**Comment by nhejazi** [comment]
Thanks for the quick reply and clarification. I'll just go ahead and update then.
