### ISSUE TITLE
SUGGESTION: More efficient code using matrixStats (>= 0.50.0)

### ISSUE THREAD

**Issue by HenrikBengtsson** [kasperdanielhansen/bsseq#8]
In [matrixStats (>= 0.50.0)](https://cran.r-project.org/package=matrixStats), which is now on CRAN, we introduce support for subsetted calculations that are [optimized both for speed and memory usage](http://www.jottr.org/2015/12/matrixstats-subsetted-calculations.html).  There are now new arguments `idxs`, `rows` and `cols` for most functions which allow you to very easily make use of this.

For your package, I believe the following functions could gain from this:
```r
$bsseq$BSmooth.fstat
rowSds(allPs[, group2, drop = FALSE], na.rm = TRUE)
rowVars(allPs[, group1, drop = FALSE])
rowVars(allPs[, group2, drop = FALSE])

$bsseq$BSmooth.tstat
rowSds(allPs[, group2, drop = FALSE], na.rm = TRUE)
rowVars(allPs[, group1, drop = FALSE])
rowVars(allPs[, group2, drop = FALSE])
```
by updating to something like:
```r
$bsseq$BSmooth.fstat
rowSds(allPs, cols = group2, na.rm = TRUE)
rowVars(allPs, cols = group1)
rowVars(allPs, cols = group2)

$bsseq$BSmooth.tstat
rowSds(allPs, cols = group2, na.rm = TRUE)
rowVars(allPs, cols = group1)
rowVars(allPs, cols = group2)
```
and adding `matrixStats (>= 0.50.0)` to your `DESCRIPTION` file.

**Comment by kasperdanielhansen** [comment]
Done.

**Comment by HenrikBengtsson** [comment]
Sorry, but `rowSums()` is in `base` and does _not_ support such subsetting, cf. commit 25426bd.

**Comment by HenrikBengtsson** [comment]
Same for `rowMeans()`.

**Comment by kasperdanielhansen** [comment]
Damn. Would you consider adding them to matrixStats to support this?

**Comment by kasperdanielhansen** [comment]
Better fix; closed.

**Comment by HenrikBengtsson** [comment]
@kasperdanielhansen, added your wish in https://github.com/HenrikBengtsson/matrixStats/issues/82.
